services:
  app:
    build:
      context: .
    container_name: travel-api
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=travel
      - DB_USERNAME=postgres
      - DB_PASSWORD=xawdfthbxawdfth2
    networks:
      - travelnet
    command: php artisan serve --host=0.0.0.0 --port=9000

  db:
    image: postgres:15
    container_name: travel-db
    environment:
      POSTGRES_DB: travel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xawdfthbxawdfth2
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - travelnet

networks:
  travelnet:

volumes:
  pgdata:
